// Regenerates src/shapes.generated.ts from the Diagramium editor's own shape
// catalogue (SHAPE_DEFS in ../../js/graphtool.js and the fork editors), so
// the player draws each node type the way the editor does — same icon, same
// render family — and cannot drift silently when the editor adds a type.
//
//   npm run sync-shapes          (MAINTAINERS ONLY — needs a checkout of the
//                                  Diagramium editor; point DIAGRAMIUM_APP at
//                                  its js/ folder if it is not ../../../js/)
//
// Contributors never need this: src/shapes.generated.ts is committed.
//
// Reads one-line shape literals: { type: 'service', ..., icon: '⚙️', render: 'iconBox', ... }
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

import { pathToFileURL } from 'node:url';
const APP = process.env.DIAGRAMIUM_APP
  ? pathToFileURL(process.env.DIAGRAMIUM_APP.replace(/\/?$/, '/'))
  : new URL('../../../js/', import.meta.url);
if (!existsSync(new URL('graphtool.js', APP))) {
  console.log('sync-shapes: the Diagramium editor source was not found — src/shapes.generated.ts left as it is.');
  process.exit(0);
}
const FILES = ['graphtool.js', 'flowchart.js', 'statemachine.js', 'swimlane.js', 'kanban.js'];
const out = {};
for (const f of FILES) {
  const url = new URL(f, APP);
  if (!existsSync(url)) continue;
  for (const line of readFileSync(url, 'utf8').split('\n')) {
    if (!/\{\s*type:\s*'/.test(line) || !/\bname:\s*'/.test(line)) continue;
    const pick = (k) => { const m = new RegExp(`\\b${k}:\\s*'([^']*)'`).exec(line); return m ? m[1] : undefined; };
    const type = pick('type');
    if (!type || out[type]) continue;                 // first definition wins
    const rec = {};
    const icon = pick('icon'), render = pick('render');
    if (icon) rec.icon = icon;
    if (render) rec.render = render;
    if (/\bcontainer:\s*true/.test(line)) rec.container = true;
    out[type] = rec;                                  // kept while scanning so the first definition still wins
  }
}
// Only types that change how the player draws them are shipped.
for (const t of Object.keys(out)) if (!Object.keys(out[t]).length) delete out[t];
const types = Object.keys(out).sort();
const body =
`/* GENERATED by scripts/sync-shapes.mjs from the Diagramium editor's SHAPE_DEFS
   — do not hand-edit; re-run the script after the editor adds or changes a
   node type. ${types.length} types. */
export interface ShapeMeta { icon?: string; render?: string; container?: boolean }
export const SHAPE_META: Record<string, ShapeMeta> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(new URL('../src/shapes.generated.ts', import.meta.url), body);
console.log(`wrote src/shapes.generated.ts (${types.length} types, ${types.filter((t) => out[t].render === 'iconBox').length} icon boxes)`);
