/* GENERATED by scripts/sync-shapes.mjs from the Diagramium editor's SHAPE_DEFS
   — do not hand-edit; re-run the script after the editor adds or changes a
   node type. 35 types. */
export interface ShapeMeta { icon?: string; render?: string; container?: boolean }
export const SHAPE_META: Record<string, ShapeMeta> = {
  "client": {
    "icon": "🖥️",
    "render": "iconBox"
  },
  "mobile": {
    "icon": "📱",
    "render": "iconBox"
  },
  "webapp": {
    "icon": "🌐",
    "render": "iconBox"
  },
  "apigateway": {
    "icon": "🚪",
    "render": "iconBox"
  },
  "loadbalancer": {
    "icon": "⚖️",
    "render": "iconBox"
  },
  "service": {
    "icon": "⚙️",
    "render": "iconBox"
  },
  "worker": {
    "icon": "🛠️",
    "render": "iconBox"
  },
  "ai": {
    "icon": "🤖",
    "render": "iconBox"
  },
  "auth": {
    "icon": "🔐",
    "render": "iconBox"
  },
  "cache": {
    "icon": "⚡",
    "render": "iconBox"
  },
  "queue": {
    "icon": "📨",
    "render": "iconBox"
  },
  "storage": {
    "icon": "🪣",
    "render": "iconBox"
  },
  "external": {
    "render": "cloud"
  },
  "cdn": {
    "icon": "🌍",
    "render": "iconBox"
  },
  "monitoring": {
    "icon": "📊",
    "render": "iconBox"
  },
  "group": {
    "render": "group",
    "container": true
  },
  "internet": {
    "icon": "🌐",
    "render": "iconBox"
  },
  "cloud": {
    "render": "cloud"
  },
  "router": {
    "icon": "📡",
    "render": "iconBox"
  },
  "switch": {
    "icon": "🔀",
    "render": "iconBox"
  },
  "firewall": {
    "icon": "🧱",
    "render": "iconBox"
  },
  "wifi": {
    "icon": "📶",
    "render": "iconBox"
  },
  "vpn": {
    "icon": "🔒",
    "render": "iconBox"
  },
  "server": {
    "icon": "🖥️",
    "render": "iconBox"
  },
  "nas": {
    "icon": "💾",
    "render": "iconBox"
  },
  "workstation": {
    "icon": "💻",
    "render": "iconBox"
  },
  "printer": {
    "icon": "🖨️",
    "render": "iconBox"
  },
  "person": {
    "icon": "🧍",
    "render": "iconBox"
  },
  "container": {
    "icon": "📦",
    "render": "iconBox"
  },
  "component": {
    "icon": "🧩",
    "render": "iconBox"
  },
  "externalSystem": {
    "icon": "☁️",
    "render": "iconBox"
  },
  "userTask": {
    "icon": "👤",
    "render": "iconBox"
  },
  "serviceTask": {
    "icon": "⚙️",
    "render": "iconBox"
  },
  "sendTask": {
    "icon": "📤",
    "render": "iconBox"
  },
  "receiveTask": {
    "icon": "📥",
    "render": "iconBox"
  }
};
